---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: book-import
  name: book-import-placement-0
  namespace: book-import
spec:
  clusterSelector:
    matchLabels:
      "usage": "development"
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: book-import
  name: book-import-placement-1
  namespace: book-import
spec:
  clusterSelector:
    matchLabels:
      "usage": "production"
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
