apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: book-import
  name: book-import
spec:
  replicas: 3
  selector:
    matchLabels:
      name: book-import
  template:
    metadata:
      labels:
        name: book-import
      annotations:
        usage-env: prod
    spec:
      containers:
        - image: quay.io/jpacker/hugo-nginx:latest
          name: book-import
          ports:
            - containerPort: 8080
              name: http-server
          resources:
            requests:
              cpu: 1000m
            limit: 
              cpu: 1000m