apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-deploy
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy
    directory:
      recurse: true
    repoURL: https://github.com/csfreak/tmxdemo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - Prune=true