apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies
  namespace: openshift-gitops
spec:
  destination:
    namespace: policies
    server: https://kubernetes.default.svc
  project: default
  source:
    path: policy
    repoURL: https://github.com/csfreak/tmxdemo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - Prune=true
      - CreateNamespace=true
      - PruneLast=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
      annotations:
        app.openshift.io/vcs-uri: "https://github.com/csfreak/tmxdemo.git"
        app.openshift.io/vcs-ref: main
